language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '8'
  - '6'
  - '4'
  - '0.12'
before_script:
  - npm prune
script:
  - npm test
  - npm run build
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
